# For more information: https://laravel.com/docs/sail
version: '3.7'
services:
  nmap_api:
    container_name: nmap_api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 8080:8080
    environment:
      - CHOKIDAR_USEPOLLING=true